### PR TITLE
Add support for TLSv1.3

### LINKED ISSUE #97: Supporting TLS 1.3
Hi there! I noticed I was getting errors in the federation tester since I had set up haproxy for TLS 1.3 only. Enabling TLS 1.2 as well resolved it, but would be nice to have the support!

Thanks for a very useful service!

### PR DESCRIPTION
**Pull request by ilmari**
This requires bumping the minimum Go version to 1.12

Closes #97

### CODE REVIEW

**Comment by richvdh** [comment]
looks plausible, but it also looks like the CI is broken, so we might have to fix that first :/

**Comment by ilmari** [comment]
@richvdh adding `GO111MODULE=on` fixed the prerequisite installation step, but I have no idea how to fix the linter not finding the prereqs.

**Comment by richvdh** [comment]
It'd be good to make fixing the CI a separate PR.

**Comment by ilmari** [comment]
@richvdh It looks like `gometalinter` just doesn't work with go 1.11 modules. It's been [deprecated and archived](https://github.com/alecthomas/gometalinter/issues/590). Apparently one should switch to [golangci-lint](https://github.com/golangci/golangci-lint).

I don't have the time nor the knowledge to do the conversion, but I think it would be a shame to block this change on that. Could we just disable the linting part of the CI for now, or merge this change regardless?

**Comment by maquis196** [comment]
I've tried to migrate to golangci (keeping the versioning the same to just at least migrate before adding 1.13), but its hitting an issue, someone who knows go able to check whats going on here? https://github.com/matrix-org/matrix-federation-tester/pull/107

**Comment by maquis196** [comment]
So my branch has been merged, if you want to rebase and give this a go again

**Comment by ilmari** [comment]
Thanks @maquis196! I've rebased it and it's all green! Fancy merging it, @babolivier?

**Pull request merged**
