### PR TITLE
Improve error handling, especially wrt .well-known checks

### LINKED ISSUE #50: "error": "No .well-known found" when well-known unused
I kinda know why it says this, but it's really unintuitive. Can we call this something like `result` instead of `error`?

### PR DESCRIPTION
**Pull request by babolivier**
This PR shows whether a `/.well-known/matrix/server` file exists for a server as a boolean rather than an error. It also removes the per-address `WellKnownInUse` value, which doesn't really make sense. Because that was the only value in `ConnectionReport.Info`, I also removed that structure. We might want to re-add it in the future if we have useful information to add there.

It also replaces error strings with instances of `ReportError` in order to handle errors the same way throughout the whole report.

Fixes #50 
Fixes https://github.com/matrix-org/fed-tester-ui/issues/1

### CODE REVIEW

**Comment by babolivier** [comment]
FTR CI fails because https://github.com/matrix-org/gomatrixserverlib/pull/116 isn't merged yet. Will need to update the vendored gomatrixserverlib once that's done.

**Comment by anoadragon453** [comment]
FYI foks will need to update the UI if this goes through.

**Comment by richvdh** [comment]
> It also replaces error strings with instances of `ReportError` in order to handle errors the same way throughout the whole report.

I am unconvinced this is the right thing to do. 

anyway, blocking this pending updates to https://github.com/matrix-org/gomatrixserverlib/pull/116

**Comment by babolivier** [comment]
Superseded by https://github.com/matrix-org/matrix-federation-tester/pull/70

**Pull request closed without merging**
